<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
    <Reference Include="tyuiu.cources.programming.interfaces">
      <HintPath>..\..\Tyuiu.SadykovSV.Sprint2\tyuiu.cources.programming.interfaces.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
